version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'inventory'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    entrypoint: ["/entrypoint.sh"]
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app
      - ./.env:/path/to/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy

  redis:
    image: redis:6.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    entrypoint: ["/celery-entrypoint.sh"]
    command: >
      bash -c "celery -A inventory_system worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_started
      # redis:
      #   condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=inventory_system.settings

volumes:
  mysql_data: