services:
  - type: web
    name: inventory-system
    region: oregon
    env: docker
    buildCommand: docker build -t inventory-system .
    startCommand: gunicorn inventory_system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: inventory-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: DB_HOST
        value: your-mysql-host.aivencloud.com
      - key: DB_PORT
        value: your-port
      - key: DB_NAME
        value: your-db-name
      - key: DB_USER
        value: your-username
      - key: DB_PASSWORD
        sync: false
  
  - type: redis
    name: inventory-redis
    region: oregon
    ipAllowList: []  # Allow all IPs, for security reasons only allow internal connections
    plan: free
    maxmemoryPolicy: noeviction # recommended policy for queues

  - type: worker
    name: celery-worker
    env: docker
    region: oregon
    buildCommand: docker build -t inventory-system .
    startCommand: celery -A inventory_system worker --loglevel=info --concurrency 4
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_system.settings
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: inventory-redis
          property: connectionString