services:
  - type: web
    name: inventory-system
    region: oregon
    env: docker
    buildCommand: docker build --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -t inventory-system .
    startCommand: gunicorn inventory_system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4

  - type: worker
    name: celery-worker
    env: docker
    region: oregon
    buildCommand: docker build --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -t inventory-system .
    startCommand: celery -A inventory_system worker --loglevel=info --concurrency 4